apiVersion: v1
kind: Service
metadata:
  labels:
    run: kafka-interaction
  name: kafka-interaction-service
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: kafka-interaction
  type: LoadBalancer
status:
  loadBalancer: {}
